const INIT_LOCATIONS = 'INIT_LOCATIONS';
const ADD_UPDATE_LOCATION = 'ADD_UPDATE_LOCATION';
const DELETE_LOCATION = 'DELETE_LOCATION';

export { INIT_LOCATIONS, ADD_UPDATE_LOCATION, DELETE_LOCATION };