const REQUESTING_LOCATIONS_START = 'REQUESTING_LOCATIONS_START';
const REQUESTING_LOCATIONS_COMPLETE = 'REQUESTING_LOCATIONS_COMPLETE';
const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS';
const FETCH_LOCATIONS_FAILURE = 'FETCH_LOCATIONS_FAILURE'
const ADD_OR_UPDATE_LOCATION = 'ADD_OR_UPDATE_LOCATION';
const REMOVE_LOCATION = 'REMOVE_LOCATION';

export {
    ADD_OR_UPDATE_LOCATION,
    REQUESTING_LOCATIONS_START,
    REQUESTING_LOCATIONS_COMPLETE,
    FETCH_LOCATIONS_FAILURE,
    FETCH_LOCATIONS_SUCCESS,
    REMOVE_LOCATION
};